# Generated by Django 5.0.3 on 2024-03-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_app", "0002_bankaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="account_no",
            new_name="Account_no",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="location",
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("body", models.TextField()),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("design", "Design"),
                            ("technology", "Technology"),
                            ("popular", "Popular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_on", models.DateTimeField(auto_now=True)),
                (
                    "artice_post_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="Location",
            field=models.TextField(blank=True),
        ),
    ]
